src/Denisov.TobaccoStore/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Denisov.TobaccoStore.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

src/Denisov.TobaccoStore/Controllers/GeneratorController.cs
using Denisov.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace Denisov.TobaccoStore.Controllers
{
    public class GeneratorController : Controller
    {
        private DenisovDbContext db;

        public GeneratorController(DenisovDbContext context)
        {
            db = context;
        }

        public IActionResult Generator()
        {
            return View();
        }

        [Authorize]
        public async Task<IActionResult> TobaccoGeneratorResult()
        {
            var tobaccos = await db.Tobaccos.ToListAsync();
            var random = new Random();
            int index = random.Next(tobaccos.Count);
            return View(tobaccos[index]);
        }

        [Authorize]
        public async Task<IActionResult> MixGeneratorResult()
        {
            var mixes = await db.Mixes.ToListAsync();
            var random = new Random();
            int index = random.Next(mixes.Count);
            return View(mixes[index]);
        }
    }
}

src/Denisov.TobaccoStore/Controllers/PersonalPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace Denisov.TobaccoStore.Controllers
{
    public class PersonalPageController : Controller
    {
        public IActionResult PersonalPage()
        {
            return View();
        }
    }
}

src/Denisov.TobaccoStore/Controllers/PlacesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Denisov.TobaccoStore.Controllers
{
    public class PlacesController : Controller
    {
        public IActionResult Places()
        {
            return View();
        }
    }
}

src/Denisov.TobaccoStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Denisov.TobaccoStore</title>
    @RenderSection("Css", required: false)
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous" />
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header__inner">
                <div class="header__logo">Denisov Tobacco Store</div>
                <nav class="nav">
                    <a class="nav__link" asp-controller="Home" asp-action="Index">Главная</a>
                    <a class="nav__link" asp-controller="Generator" asp-action="Generator">Генератор</a>
                    <a class="nav__link" asp-controller="Places" asp-action="Places">Места</a>
                    <a class="nav__link" asp-controller="About" asp-action="About">О нас</a>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav__link" asp-controller="PersonalPage" asp-action="PersonalPage">@User.Identity.Name</a>
                        <form method="post" class="nav__link" asp-controller="Account" asp-action="Logout">
                            <input class="button__logout" type="submit" value="Выход" />
                        </form>
                    }
                    else
                    {
                        <a class="nav__link" asp-controller="Account" asp-action="Login">Войти</a>
                        <a class="nav__link" asp-controller="Account" asp-action="Register">Зарегистрироваться</a>
                    }
                </nav>
            </div>
        </div>
    </header>

    <div class="container" style="justify-content: center;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted"> &copy; 2020 - Denisov.TobaccoStore - <a asp-controller="Home" asp-action="Privacy">Privacy</a></span>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>